/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.gui;

import calculadora.backend.calculosDiscretos;
import javax.swing.JOptionPane;

/**
 *
 * @author ricardo
 */
public class calculosDiscretosFrame extends javax.swing.JInternalFrame {

    calculosDiscretos discretos;
    public calculosDiscretosFrame() {
        this.discretos = new calculosDiscretos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        discretosComboBox = new javax.swing.JComboBox<>();
        enteroNText = new javax.swing.JTextField();
        enteroRText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        discretosButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        resultadoText = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setTitle("CALCULOS DISCRETOS");

        discretosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factorial", "Permutacion", "Combinacion" }));
        discretosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discretosComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Entero n");

        jLabel2.setText("Entero r");

        discretosButton.setText("Calcular");
        discretosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discretosButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discretosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enteroNText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(discretosButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(enteroRText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(resultadoText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(discretosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enteroNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(enteroRText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(discretosButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(resultadoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void discretosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discretosComboBoxActionPerformed
        switch (discretosComboBox.getSelectedIndex()) {
            case 0:
                enteroRText.setEditable(false);
                break;
            case 1:
                enteroNText.setEditable(true);
                enteroRText.setEditable(true);
                break;
            case 2:
                enteroNText.setEditable(true);
                enteroRText.setEditable(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_discretosComboBoxActionPerformed

    private void discretosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discretosButtonActionPerformed
        switch (discretosComboBox.getSelectedIndex()) {
            case 0:
                try{
                    discretos.generarFactorial(Integer.parseInt(enteroNText.getText()));
                    resultadoText.setText(Integer.toString(discretos.getResultadoFactorial()));
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"ERROR\nVerifique el dato ingresado.","Error de Tipeo",JOptionPane.ERROR_MESSAGE);
                } 
                
                break;
            case 1:
                try{
                    discretos.calcularPermutacion(Integer.parseInt(enteroNText.getText()), Integer.parseInt(enteroRText.getText()));
                    resultadoText.setText(Integer.toString(discretos.getResultadoFactorial()));
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"ERROR\nVerifique el dato ingresado.","Error de Tipeo",JOptionPane.ERROR_MESSAGE);
                } 
                
                break;
            case 2:
                try{
                    discretos.calcularCombinacion(Integer.parseInt(enteroNText.getText()), Integer.parseInt(enteroRText.getText()));
                    resultadoText.setText(Integer.toString(discretos.getResultadoFactorial()));
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"ERROR\nVerifique el dato ingresado.","Error de Tipeo",JOptionPane.ERROR_MESSAGE);
                } 
                
                break;
            default:
                break;
        }
    }//GEN-LAST:event_discretosButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton discretosButton;
    private javax.swing.JComboBox<String> discretosComboBox;
    private javax.swing.JTextField enteroNText;
    private javax.swing.JTextField enteroRText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField resultadoText;
    // End of variables declaration//GEN-END:variables
}
