/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.gui;
import calculadora.gui.CalcuBasicaInterfaz;
import calculadora.gui.calculosDiscretosFrame;
import calculadora.gui.conversionesNumericas;
import java.awt.Dimension;

/**
 *
 * @author fabricio
 */
public class CalculadoraInterfaz extends javax.swing.JFrame {

    private calculosDiscretosFrame calculosDiscretosFrame;
    private conversionesNumericas conversionesNumericasFrame;
    private CalcuBasicaInterfaz cbi;
    private acerca acerca;
    private Dimension desktopSize;
    
    public CalculadoraInterfaz() {
        calculosDiscretosFrame = new calculosDiscretosFrame();
        conversionesNumericasFrame = new conversionesNumericas();
        cbi = new CalcuBasicaInterfaz();
        acerca = new acerca();
        initComponents();
        this.desktopSize = this.DesktopCalculadora.getSize();
        this.DesktopCalculadora.add(calculosDiscretosFrame);
        this.DesktopCalculadora.add(conversionesNumericasFrame);
        this.DesktopCalculadora.add(cbi);
        this.DesktopCalculadora.add(acerca);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopCalculadora = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        calculadoraBasica = new javax.swing.JMenuItem();
        calculadoraDiscreta = new javax.swing.JMenuItem();
        convertirNumeros = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        opcionSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jMenu1.setText("Operaciones");

        calculadoraBasica.setText("Calculos Basicos");
        calculadoraBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadoraBasicaActionPerformed(evt);
            }
        });
        jMenu1.add(calculadoraBasica);

        calculadoraDiscreta.setText("Calculos Discretos");
        calculadoraDiscreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadoraDiscretaActionPerformed(evt);
            }
        });
        jMenu1.add(calculadoraDiscreta);

        convertirNumeros.setText("Convertir Numeros");
        convertirNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirNumerosActionPerformed(evt);
            }
        });
        jMenu1.add(convertirNumeros);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Opcion");

        jMenuItem1.setText("Acerca de");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        opcionSalir.setText("Salir");
        opcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSalirActionPerformed(evt);
            }
        });
        jMenu3.add(opcionSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopCalculadora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertirNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirNumerosActionPerformed
        Dimension frameSize = this.conversionesNumericasFrame.getSize();
        this.conversionesNumericasFrame.setLocation((this.desktopSize.width - frameSize.width) / 2, 0);
        this.conversionesNumericasFrame.show();
    }//GEN-LAST:event_convertirNumerosActionPerformed

    private void opcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_opcionSalirActionPerformed

    private void calculadoraBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadoraBasicaActionPerformed
        Dimension frameSize = this.cbi.getSize();
        this.cbi.setLocation((this.desktopSize.width - frameSize.width) / 2, 0);
        this.cbi.show();
    }//GEN-LAST:event_calculadoraBasicaActionPerformed

    private void calculadoraDiscretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadoraDiscretaActionPerformed
        Dimension frameSize = this.calculosDiscretosFrame.getSize();
        this.calculosDiscretosFrame.setLocation((this.desktopSize.width - frameSize.width) / 2, 0);
        this.calculosDiscretosFrame.show();
    }//GEN-LAST:event_calculadoraDiscretaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Dimension frameSize = this.acerca.getSize();
        this.acerca.setLocation((this.desktopSize.width - frameSize.width) / 2, 0);
        this.acerca.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopCalculadora;
    private javax.swing.JMenuItem calculadoraBasica;
    private javax.swing.JMenuItem calculadoraDiscreta;
    private javax.swing.JMenuItem convertirNumeros;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem opcionSalir;
    // End of variables declaration//GEN-END:variables
}
