/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.gui;

import calculadora.backend.conversiones;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/**
 *
 * @author ricardo
 */
public class conversionesNumericas extends javax.swing.JInternalFrame {
    
    conversiones conversiones;
    public conversionesNumericas() {
        this.conversiones = new conversiones();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conversionesComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        numeroText = new javax.swing.JTextField();
        convertirButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        resultadoText = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("CONVERSIONES NUMERICAS");

        conversionesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Binario", "A Octal", "A Hexadecimal" }));

        jLabel1.setText("No. Decimal.");

        convertirButton.setText("Convertir");
        convertirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conversionesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertirButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numeroText, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(resultadoText))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conversionesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numeroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(convertirButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(resultadoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirButtonActionPerformed
        switch (conversionesComboBox.getSelectedIndex()) {
            case 0:
                try{
                    conversiones.convertirABinario(Integer.parseInt(numeroText.getText()));
                    resultadoText.setText(conversiones.getResultado());
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"ERROR\nVerifique el dato ingresado.","Error de Tipeo",JOptionPane.ERROR_MESSAGE);
                }   
                break;
            case 1:
                try{
                    conversiones.convertirAOctal(Integer.parseInt(numeroText.getText()));
                    resultadoText.setText(conversiones.getResultado());
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"ERROR\nVerifique el dato ingresado.","Error de Tipeo",JOptionPane.ERROR_MESSAGE);
                } 
                break;
            case 2:
                try{
                    conversiones.convertirAHexadecimal(Integer.parseInt(numeroText.getText()));
                    resultadoText.setText(conversiones.getResultado());
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"ERROR\nVerifique el dato ingresado.","Error de Tipeo",JOptionPane.ERROR_MESSAGE);
                } 
                break;
            default:
                break;
        }
    }//GEN-LAST:event_convertirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> conversionesComboBox;
    private javax.swing.JButton convertirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numeroText;
    private javax.swing.JTextField resultadoText;
    // End of variables declaration//GEN-END:variables
}
